 drop table if exists course;
 drop table if exists course_enrollment;
 drop table if exists course_fee;
 drop table if exists course_timings;
 drop table if exists fee_payment;
 drop table if exists instructor;
 drop table if exists sequence_generator;
 drop table if exists student;
 create table course (id bigint not null, created_by varchar(50) not null, created_date datetime(6), last_modified_by varchar(50), last_modified_date datetime(6), course_code varchar(255) not null, course_name varchar(255) not null, instructor_id bigint, primary key (id)) engine=InnoDB;
 create table course_enrollment (id bigint not null, course_id bigint, student_id bigint, primary key (id)) engine=InnoDB;
 create table course_fee (id bigint not null, cost bigint not null, duration bigint not null, primary key (id)) engine=InnoDB;
 create table course_timings (id bigint not null, end_date datetime(6) not null, start_date datetime(6) not null, course_id bigint, primary key (id)) engine=InnoDB;
 create table fee_payment (id bigint not null, fee_amount bigint not null, enroll_id bigint, primary key (id)) engine=InnoDB;
 create table instructor (id bigint not null, created_by varchar(50) not null, created_date datetime(6), last_modified_by varchar(50), last_modified_date datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
 create table sequence_generator (next_val bigint) engine=InnoDB;
 insert into sequence_generator values ( 1 );
 create table student (id bigint not null, created_by varchar(50) not null, created_date datetime(6), last_modified_by varchar(50), last_modified_date datetime(6), activated bit not null, activation_key varchar(20), email varchar(254), first_name varchar(50), image_url varchar(256), lang_key varchar(10), last_name varchar(50), login varchar(50) not null, password_hash varchar(60) not null, reset_date datetime(6), reset_key varchar(20), primary key (id)) engine=InnoDB;
 alter table student add constraint UK_fe0i52si7ybu0wjedj6motiim unique (email);
 alter table student add constraint UK_t5vpeh9gchmd6j66jiyr07trn unique (login);
 alter table course add constraint FKqk2yq2yk124dhlsilomy36qr9 foreign key (instructor_id) references instructor (id);
 alter table course_enrollment add constraint FKmdu3eh7r8fvaemtwyps4dtqoh foreign key (course_id) references course (id);
 alter table course_enrollment add constraint FKc5aniwy1axq8343gtpm50sdlj foreign key (student_id) references student (id);
 alter table course_fee add constraint FK5p2y9twfu027qih5ukli85tsa foreign key (id) references course (id);
 alter table course_timings add constraint FKeurvr4v0554qlvr4fboe3ta1g foreign key (course_id) references course (id);
 alter table fee_payment add constraint FK9hrndi3xs85a26erwrhp274tl foreign key (enroll_id) references course_enrollment (id);